#!/usr/bin/env node
/**
 * Lwang Black — Interactive setup
 * --------------------------------
 *  • Prompts for the API keys / secrets the backend needs.
 *  • Writes them to backend/.env, preserving any existing values.
 *  • Auto-generates strong random JWT secrets the first time it runs.
 *
 * Usage:
 *    node scripts/setup.js              # interactive
 *    node scripts/setup.js --no-prompt  # only fill missing JWT secrets, don't ask
 *
 * Re-run anytime — existing keys are kept unless you explicitly type a new value.
 */
'use strict';

const fs       = require('fs');
const path     = require('path');
const readline = require('readline');
const crypto   = require('crypto');

const ROOT       = path.resolve(__dirname, '..');
const ENV_FILE   = path.join(ROOT, 'backend', '.env');
const ENV_SAMPLE = path.join(ROOT, 'backend', '.env.example');

const args = new Set(process.argv.slice(2));
const NO_PROMPT = args.has('--no-prompt') || args.has('-y');

// ── small ANSI helpers (no chalk dep) ──────────────────────────────────────
const c = {
  reset: '\x1b[0m', dim: '\x1b[2m', bold: '\x1b[1m',
  red: '\x1b[31m', green: '\x1b[32m', yellow: '\x1b[33m',
  blue: '\x1b[34m', magenta: '\x1b[35m', cyan: '\x1b[36m',
};
const useColor = process.stdout.isTTY;
const fmt = (col, s) => useColor ? col + s + c.reset : s;

function header(title) {
  console.log('\n' + fmt(c.bold + c.cyan, '─── ' + title + ' '.padEnd(60 - title.length, '─')));
}
function note(msg)    { console.log(fmt(c.dim, '   ' + msg)); }
function success(msg) { console.log(fmt(c.green, '   ✓ ' + msg)); }
function warn(msg)    { console.log(fmt(c.yellow, '   ! ' + msg)); }

// ── env file parsing / writing ─────────────────────────────────────────────
function parseEnv(text) {
  const out = {};
  if (!text) return out;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const idx = line.indexOf('=');
    if (idx < 0) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1);
    // Honour quoted values verbatim; strip inline comments only on unquoted ones.
    const trimmedVal = val.trim();
    if ((trimmedVal.startsWith('"') && trimmedVal.endsWith('"')) ||
        (trimmedVal.startsWith("'") && trimmedVal.endsWith("'"))) {
      val = trimmedVal.slice(1, -1);
    } else {
      // Strip trailing inline comment ( "value   # comment" → "value" ).
      const hashIdx = val.indexOf(' #');
      if (hashIdx >= 0) val = val.slice(0, hashIdx);
      val = val.trim();
    }
    out[key] = val;
  }
  return out;
}

function loadCurrent() {
  if (fs.existsSync(ENV_FILE)) return parseEnv(fs.readFileSync(ENV_FILE, 'utf8'));
  if (fs.existsSync(ENV_SAMPLE)) return parseEnv(fs.readFileSync(ENV_SAMPLE, 'utf8'));
  return {};
}

function quoteIfNeeded(v) {
  if (v === '' || v == null) return '';
  if (/[\s#"'`$\\]/.test(v)) return JSON.stringify(v);
  return v;
}

function writeEnv(env) {
  const ordered = Object.keys(env).sort((a, b) => a.localeCompare(b));
  const lines = [
    '# Generated by scripts/setup.js — safe to edit by hand.',
    '# Re-run `node scripts/setup.js` to update interactively.',
    '',
  ];
  for (const k of ordered) lines.push(`${k}=${quoteIfNeeded(env[k] || '')}`);
  lines.push('');
  fs.mkdirSync(path.dirname(ENV_FILE), { recursive: true });
  fs.writeFileSync(ENV_FILE, lines.join('\n'), { mode: 0o600 });
}

// ── prompt helper ──────────────────────────────────────────────────────────
function prompt(rl, question, def) {
  return new Promise(resolve => {
    const defStr = def ? fmt(c.dim, ` [${def.length > 36 ? def.slice(0, 33) + '…' : def}]`) : '';
    rl.question(fmt(c.cyan, '   ? ') + question + defStr + ' › ', ans => {
      const v = ans.trim();
      resolve(v === '' ? (def || '') : v);
    });
  });
}

async function ask(rl, env, key, label, opts = {}) {
  const def = env[key] || opts.default || '';
  if (NO_PROMPT) {
    if (!env[key] && opts.default) env[key] = opts.default;
    return env[key] || '';
  }
  const val = await prompt(rl, `${label}${opts.hint ? fmt(c.dim, '  ' + opts.hint) : ''}`, def);
  env[key] = val;
  return val;
}

async function askYesNo(rl, question, defaultYes = true) {
  if (NO_PROMPT) return defaultYes;
  const def = defaultYes ? 'Y/n' : 'y/N';
  const ans = (await prompt(rl, `${question} (${def})`, '')).toLowerCase();
  if (!ans) return defaultYes;
  return ans.startsWith('y');
}

function strongSecret(bytes = 48) {
  return crypto.randomBytes(bytes).toString('base64').replace(/[+/=]/g, '').slice(0, 64);
}

// ── main flow ──────────────────────────────────────────────────────────────
async function main() {
  console.log(fmt(c.bold + c.magenta, '\nLwang Black — interactive setup'));
  console.log(fmt(c.dim, 'Writes to ' + path.relative(ROOT, ENV_FILE)));
  console.log(fmt(c.dim, 'Press ENTER to keep the existing value (shown in brackets).\n'));

  const env = loadCurrent();
  const rl  = readline.createInterface({ input: process.stdin, output: process.stdout });

  // ── always-needed: server + JWT ──────────────────────────────────────────
  header('Core server');
  await ask(rl, env, 'PORT',          'API port',                       { default: '3001' });
  await ask(rl, env, 'NODE_ENV',      'Node environment (development|production)', { default: 'development' });

  // Auto-generate JWT secrets on first run (or if still on the insecure default).
  const insecureJwt = !env.JWT_SECRET ||
    env.JWT_SECRET === 'lwangblack-jwt-secret-change-in-production' ||
    env.JWT_SECRET.startsWith('change-this');
  if (insecureJwt) {
    env.JWT_SECRET = strongSecret();
    success('Generated strong JWT_SECRET');
  }
  const insecureRefresh = !env.JWT_REFRESH_SECRET ||
    env.JWT_REFRESH_SECRET === 'lwangblack-refresh-secret' ||
    env.JWT_REFRESH_SECRET.startsWith('change-this');
  if (insecureRefresh) {
    env.JWT_REFRESH_SECRET = strongSecret();
    success('Generated strong JWT_REFRESH_SECRET');
  }
  if (!env.JWT_EXPIRES_IN)         env.JWT_EXPIRES_IN = '12h';
  if (!env.JWT_REFRESH_EXPIRES_IN) env.JWT_REFRESH_EXPIRES_IN = '7d';

  if (!env.DEFAULT_ADMIN_PASSWORD) env.DEFAULT_ADMIN_PASSWORD = 'changeme-' + strongSecret(6);
  await ask(rl, env, 'DEFAULT_ADMIN_PASSWORD', 'Default admin password (change after first login)');

  // ── database ─────────────────────────────────────────────────────────────
  header('Database');
  note('Without DATABASE_URL the API runs in in-memory demo mode (orders lost on restart).');
  await ask(rl, env, 'DATABASE_URL', 'Postgres URL', {
    default: env.DATABASE_URL || 'postgres://lwangblack:lwangblack_secret@localhost:5432/lwangblack',
    hint: '(leave default for local docker-compose)',
  });
  await ask(rl, env, 'REDIS_URL', 'Redis URL (optional, for session revocation)', {
    default: env.REDIS_URL || '',
    hint: '(blank to skip)',
  });

  // ── site / cors ──────────────────────────────────────────────────────────
  header('Frontend / CORS');
  await ask(rl, env, 'SITE_URL',    'Production site URL', { default: env.SITE_URL || 'https://www.lwangblack.co' });
  await ask(rl, env, 'FRONTEND_URL','Storefront URL for payment return links', { default: env.FRONTEND_URL || env.SITE_URL || 'https://www.lwangblack.co' });
  await ask(rl, env, 'CORS_ORIGIN', 'Comma-separated allowed CORS origins', {
    default: env.CORS_ORIGIN || 'https://www.lwangblack.co,https://lwangblack.co,http://localhost:5173,http://localhost:3000',
  });
  await ask(rl, env, 'LWB_API_BASE', 'API base URL the storefront calls (e.g. https://YOUR-API.onrender.com/api)', {
    default: env.LWB_API_BASE || '',
    hint: '(blank = same-origin /api via Vercel proxy)',
  });
  await ask(rl, env, 'BACKEND_URL', 'Render API origin (for Vercel /api proxy)', {
    default: env.BACKEND_URL || '',
    hint: '(blank to skip)',
  });
  await ask(rl, env, 'GTM_CONTAINER_ID', 'Google Tag Manager ID (e.g. GTM-ABC1234)', {
    default: env.GTM_CONTAINER_ID || '',
    hint: '(blank = strip GTM blocks at build time)',
  });

  // ── stripe ───────────────────────────────────────────────────────────────
  if (await askYesNo(rl, 'Configure Stripe (cards / Apple Pay / Google Pay / Afterpay)?', true)) {
    header('Stripe');
    note('Get keys at https://dashboard.stripe.com/developers/api-keys');
    await ask(rl, env, 'STRIPE_SECRET_KEY',      'Stripe secret key (sk_test_… / sk_live_…)');
    await ask(rl, env, 'STRIPE_PUBLISHABLE_KEY', 'Stripe publishable key (pk_test_… / pk_live_…)');
    await ask(rl, env, 'STRIPE_WEBHOOK_SECRET',  'Stripe webhook signing secret (whsec_…)', {
      hint: '(leave blank if you have not registered the webhook yet)',
    });
    await ask(rl, env, 'STRIPE_MODE', 'Stripe mode (test|live)', { default: env.STRIPE_MODE || 'test' });
  }

  // ── paypal ───────────────────────────────────────────────────────────────
  if (await askYesNo(rl, 'Configure PayPal?', true)) {
    header('PayPal');
    note('Get credentials at https://developer.paypal.com/dashboard/applications');
    await ask(rl, env, 'PAYPAL_CLIENT_ID',     'PayPal client ID');
    await ask(rl, env, 'PAYPAL_CLIENT_SECRET', 'PayPal client secret');
    await ask(rl, env, 'PAYPAL_MODE',          'PayPal mode (sandbox|live)', { default: env.PAYPAL_MODE || 'sandbox' });
    env.PAYPAL_LIVE = (env.PAYPAL_MODE === 'live') ? 'true' : 'false';
  }

  // ── nepal payments ───────────────────────────────────────────────────────
  if (await askYesNo(rl, 'Configure Nepal payment gateways (eSewa / Khalti / Nabil)?', false)) {
    header('eSewa');
    note('https://developer.esewa.com.np/');
    await ask(rl, env, 'ESEWA_MERCHANT_ID', 'eSewa merchant ID', { default: env.ESEWA_MERCHANT_ID || 'EPAYTEST' });
    await ask(rl, env, 'ESEWA_SECRET_KEY',  'eSewa secret key',  { default: env.ESEWA_SECRET_KEY  || '8gBm/:&EnhH.1/q' });
    await ask(rl, env, 'ESEWA_LIVE',        'eSewa live? (true|false)', { default: env.ESEWA_LIVE || 'false' });

    header('Khalti');
    note('https://docs.khalti.com/');
    await ask(rl, env, 'KHALTI_SECRET_KEY', 'Khalti secret key (live_secret_key_…)');
    await ask(rl, env, 'KHALTI_PUBLIC_KEY', 'Khalti public key (live_public_key_…)');
    await ask(rl, env, 'KHALTI_LIVE',       'Khalti live? (true|false)', { default: env.KHALTI_LIVE || 'false' });

    header('Nabil Bank');
    note('Contact Nabil corporate for sandbox credentials.');
    await ask(rl, env, 'NABIL_MERCHANT_ID', 'Nabil merchant ID');
    await ask(rl, env, 'NABIL_API_KEY',     'Nabil API key');
    await ask(rl, env, 'NABIL_SECRET_KEY',  'Nabil secret key');
    await ask(rl, env, 'NABIL_LIVE',        'Nabil live? (true|false)', { default: env.NABIL_LIVE || 'false' });
  }

  // ── COD ──────────────────────────────────────────────────────────────────
  await ask(rl, env, 'COD_ENABLED_COUNTRIES', 'COD: comma-separated ISO codes, or * for all', {
    default: env.COD_ENABLED_COUNTRIES || 'NP',
    hint: '(set to "" to disable Cash on Delivery)',
  });

  // ── logistics ────────────────────────────────────────────────────────────
  if (await askYesNo(rl, 'Configure logistics carriers (Pathao / AusPost / USPS / etc.)?', false)) {
    header('Pathao (Nepal)');
    await ask(rl, env, 'PATHAO_CLIENT_ID',       'Pathao client ID');
    await ask(rl, env, 'PATHAO_CLIENT_SECRET',   'Pathao client secret');
    await ask(rl, env, 'PATHAO_CLIENT_EMAIL',    'Pathao account email');
    await ask(rl, env, 'PATHAO_CLIENT_PASSWORD', 'Pathao account password');
    await ask(rl, env, 'PATHAO_STORE_ID',        'Pathao store ID');

    header('Australia Post');
    await ask(rl, env, 'AUSPOST_API_KEY',        'AusPost API key');
    await ask(rl, env, 'AUSPOST_ACCOUNT_NUMBER', 'AusPost MyPost Business account number');
    await ask(rl, env, 'AUSPOST_PASSWORD',       'AusPost MyPost Business password');

    header('USPS');
    await ask(rl, env, 'USPS_USER_ID',  'USPS Web Tools user ID');
    await ask(rl, env, 'USPS_PASSWORD', 'USPS password');

    header('NZ Post');
    await ask(rl, env, 'NZPOST_API_KEY',       'NZ Post API key');
    await ask(rl, env, 'NZPOST_CLIENT_ID',     'NZ Post OAuth client ID');
    await ask(rl, env, 'NZPOST_CLIENT_SECRET', 'NZ Post OAuth client secret');
    await ask(rl, env, 'NZPOST_SITE_CODE',     'NZ Post site code');

    header('Chit Chats (Canada)');
    await ask(rl, env, 'CHITCHATS_API_KEY', 'Chit Chats API key');
  }

  // ── email ────────────────────────────────────────────────────────────────
  if (await askYesNo(rl, 'Configure SendGrid email (order confirmations, contact form)?', false)) {
    header('SendGrid');
    await ask(rl, env, 'SENDGRID_API_KEY',   'SendGrid API key (SG.…)');
    await ask(rl, env, 'SENDGRID_FROM_EMAIL', 'From email', { default: env.SENDGRID_FROM_EMAIL || 'brewed@lwangblack.co' });
    await ask(rl, env, 'SENDGRID_FROM_NAME',  'From name',  { default: env.SENDGRID_FROM_NAME  || 'Lwang Black' });
  }

  // ── sms ──────────────────────────────────────────────────────────────────
  if (await askYesNo(rl, 'Configure Twilio SMS notifications?', false)) {
    header('Twilio');
    await ask(rl, env, 'TWILIO_ACCOUNT_SID', 'Twilio Account SID');
    await ask(rl, env, 'TWILIO_AUTH_TOKEN',  'Twilio Auth Token');
    await ask(rl, env, 'TWILIO_FROM_NUMBER', 'Twilio from number (e.g. +14155551234)');
    env.TWILIO_FROM_PHONE = env.TWILIO_FROM_NUMBER;
  }

  rl.close();

  // ── strip empty placeholder defaults so warnings stay loud ───────────────
  for (const k of Object.keys(env)) {
    if (typeof env[k] === 'string' && env[k].toLowerCase().includes('placeholder')) env[k] = '';
    if (typeof env[k] === 'string' && env[k].includes('your_') && env[k].includes('_here')) env[k] = '';
  }

  writeEnv(env);

  console.log('');
  success(`Wrote ${env && Object.keys(env).length} keys to ${path.relative(ROOT, ENV_FILE)}`);

  // ── final guidance ───────────────────────────────────────────────────────
  const blockers = [];
  if (!env.DATABASE_URL || env.DATABASE_URL.includes('localhost'))
    blockers.push('DATABASE_URL points at localhost — fine for dev, but production needs a real Postgres.');
  if (!env.STRIPE_SECRET_KEY) blockers.push('Stripe is not configured → card / Apple Pay / Afterpay checkout will return 503.');
  if (!env.PAYPAL_CLIENT_ID)  blockers.push('PayPal is not configured → PayPal checkout will return 503.');

  if (blockers.length) {
    console.log('');
    warn('Pending items:');
    for (const b of blockers) warn('  • ' + b);
  }
  console.log('');
  console.log('Next steps:');
  console.log('  • npm install           (project root + admin-dashboard)');
  console.log('  • cd backend && npm install');
  console.log('  • npm run preview:stack (build + run API + storefront)');
  console.log('');
}

main().catch(err => {
  console.error(fmt(c.red, '\n[setup] failed: ' + (err && err.message || err)));
  process.exit(1);
});
